import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import lightTheme from "./light.theme";
import { CssBaseline } from "@mui/material";
import Container from "@mui/material/Container";
import Header from "./components/layout/header";
import { Roboto_Slab } from "next/font/google";

//Fonts

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AppRouterCacheProvider>
        <ThemeProvider theme={lightTheme}>
          
          <CssBaseline />
          <Header />
          <Container>
            {children}
          </Container>
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
